### ISSUE TITLE
Reading image

### ISSUE THREAD

**Issue by hasanAjsf** [gen2brain/go-fitz#33] opened 2021-08-02 06:54 UTC
Hi, this is not an issue in the package itself, but something may you be able to help with.

While reading 'pdf' files, some times I stuck with the file being a 'scan' rather than clean 'pdf' in this case it is appearing as image, and can not read it with this package:
1. Is there a way to get notified that this 'pdf' is unreadable, to avoid 'panic'?
2. Is there a way to read the file even if it is scan?

My thought I may use another package to read image, like [tesseract](https://github.com/UB-Mannheim/tesseract) if failed to read using 'go-fitz'.

Thanks

**Comment by gen2brain** [comment] 2021-08-02 11:29
This is related to https://github.com/gen2brain/go-fitz/issues/29 and fz_try/fz_catch, mupdf probably use setjmp/longjmp in C, not sure if there are still issues with that in Go. Will need to check.

**Comment by gen2brain** [comment] 2022-06-21 07:59
Closing as duplicate of issue #29.

**Closed by gen2brain** 2022-06-21 07:59 UTC
