### ISSUE TITLE
Broken XREF Repair Crash

### ISSUE THREAD

**Issue by nouritsu** [gen2brain/go-fitz#68] opened 2022-11-25 06:09 UTC
My test data contains a file with a broken xref table.
The code appears to crash when I call the fitz.New() method on my file.
  
Here is the output-
```
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
error: array not closed before end of file
error: aborting process from uncaught error!
```

My function let's call it read_pdf() takes in a file path and returns (string, error). It is completely functional for all types of pdfs (text, images etc.). However when a corrupted file is passed it panics and halts program execution.
  
I have already tried putting in a
```go
defer func() {
	if err := recover(); err != nil {
		logrus.Errorf("Error parsing PDF file %v", fpath)
	}
}()
```
inside my read_pdf function but it appears the function still panics. The panic occurs in fitz.New() for sure because any lines after it are not executed.

**Comment by gen2brain** [comment] 2022-11-25 11:02
This seems to be a duplicate of https://github.com/gen2brain/go-fitz/issues/57.

**Closed by gen2brain** 2022-11-25 11:02 UTC

**Comment by gen2brain** [comment] 2023-04-29 13:46
This should be fixed in https://github.com/gen2brain/go-fitz/commit/f15918d712b55047e829b1fe6ce0b46651ca0e40.
