### ISSUE TITLE
not enough data to determine image format

### ISSUE THREAD

**Issue by helios741** [gen2brain/go-fitz#72] opened 2023-01-04 09:46 UTC
Hello, I am very happy to use this lib, but today I meet a problem for some special pdf, which has follow:
```shell
error: not enough data to determine image format
error: aborting process from uncaught error!
```

i use this demo:
```golang
func TestA(t *testing.T) {
	doc, err := fitz.New("aaa.pdf")
	if err != nil {
		t.Error(err)
		return
	}
	img, err := doc.Image(0)
	if err != nil {
		panic(err)
	}

	f, err := os.Create("aaa.png")
	if err != nil {
		panic(err)
	}

	err = jpeg.Encode(f, img, &jpeg.Options{jpeg.DefaultQuality})
	if err != nil {
		panic(err)
	}

	f.Close()
}

```

[aaa.pdf link](https://github.com/helios741/myblog/blob/new/learn_go/aaa.pdf)

I find  that [C.fz_run_page](https://github.com/gen2brain/go-fitz/blob/master/fitz.go#L217) occur error.

please how to fix it.

**Comment by gen2brain** [comment] 2023-01-12 06:59
Is this related to https://github.com/gen2brain/go-fitz/issues/57, what do you think should be fixed? If mupdf cannot parse the file, that is it, unless it is related to 57.

**Comment by gen2brain** [comment] 2023-04-25 12:07
Looks like it is related to #57 but not confirmed. Reopen if that is not the case.

**Closed by gen2brain** 2023-04-25 12:07 UTC

**Comment by gen2brain** [comment] 2023-04-29 13:46
This should be fixed in https://github.com/gen2brain/go-fitz/commit/f15918d712b55047e829b1fe6ce0b46651ca0e40.
