### ISSUE TITLE
error: cannot find startxref

### ISSUE THREAD

**Issue by vishwastawar** [gen2brain/go-fitz#30] opened 2021-06-14 13:25 UTC
whenever I try to run code on a malformed or corrupted pdf file it throws a fatal error which is given below also I have attached the corrupted  pdf file 
[test.pdf](https://github.com/gen2brain/go-fitz/files/6648547/test.pdf)
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
error: array not closed before end of file
uncaught error: array not closed before end of file
exit status 1

**Comment by gen2brain** [comment] 2021-06-15 14:17
Thanks for the test file, I will see if I can make something with it. Not sure when exactly I will find time.
Btw. I was not able to open document in any app, GUI apps, pdftotext etc.

**Comment by vishwastawar** [comment] 2021-06-16 12:02
basically, that test file is corrupted and that file will not open in any  GUI apps as well,i have created that test scenario to test my code and I found that this package is not able to handle such corrupted files scenarios it throws the fatal error instead of any exception.

**Comment by gen2brain** [comment] 2022-06-21 07:59
Closing as duplicate of issue #29.

**Closed by gen2brain** 2022-06-21 07:59 UTC
