### ISSUE TITLE
my service crash in new verion go-fitz

### ISSUE THREAD

**Issue by TimRazumov** [gen2brain/go-fitz#29] opened 2021-05-28 05:59 UTC
after upgrading to version v1.18.0 my programm crash with intarnal go-fitz error:
```
warning: cannot load object (19 0 R) into cache
error: aborting process from uncaught error!
```
in version v0.0.0-20210316172528-f0a07eb93909 his was not

**Comment by gen2brain** [comment] 2021-05-28 17:33
Does that happen with all documents or you have only some that are problematic? In bindings, errors are not "caught", if that is something internal to mupdf I cannot help.

**Comment by TimRazumov** [comment] 2021-05-29 11:08
https://github.com/ArtifexSoftware/mupdf/blob/master/source/pdf/pdf-xref.c#L2280
https://github.com/ArtifexSoftware/mupdf/blob/master/source/fitz/error.c#L153

**Comment by TimRazumov** [comment] 2021-05-30 08:42
in doc mupdf. it seems your wrapper doesn't have this processing. 
will it be difficult for you to add this?

![image](https://user-images.githubusercontent.com/56147892/120097941-da062880-c13b-11eb-9d64-05ecd3b4385c.png)

**Comment by TimRazumov** [comment] 2021-06-08 14:55
Hello. have any ideas how you can fix this?

**Comment by gen2brain** [comment] 2021-06-08 15:02
I was not able to reproduce with files I usually use for testing. I don't have time to mess with this currently, also, if you or someone else can fix this, I accept PRs.

**Comment by diegobernardes** [comment] 2021-06-09 12:25
I think the only way of solving this problem is using Go as a simple glue layer instead of directly interacting with the library. I don't think it's possible at all to use MuPDF try/catch mechanism directly with Go. 

I've been working on a wrapper of MuPDF with Go that is very specific for the company that I'm working for, but it may give some ideas: https://github.com/nitro/lazypdf

**Comment by TimRazumov** [comment] 2021-06-09 15:48
hello @diegobernardes. I saw your library, but it's not entirely clear to me how to install it, which I described in this issue: https://github.com/Nitro/lazypdf/issues/51

**Comment by gen2brain** [comment] 2022-06-21 10:24
Closing this in favor of https://github.com/gen2brain/go-fitz/issues/57.

**Closed by gen2brain** 2022-06-21 10:24 UTC

**Comment by gen2brain** [comment] 2023-04-29 13:46
This should be fixed in https://github.com/gen2brain/go-fitz/commit/f15918d712b55047e829b1fe6ce0b46651ca0e40.
